Pin memory
cloudfoundry/bosh-vsphere-cpi-release pull request #384
Opened 2024-07-15 10:32 UTC by rkoster

Rebase on original PR failed: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/pull/281 so opening new PR here.

2024-07-23 19:26 UTC, ystros commented
Opted against adding a full integration spec, since the feature takes a multiple of the ESXi host CPU MHz, which wouldn't be very predictable depending on the environment the tests are run.

We did manually deploy a VM using a VM extension to set `cpu_reserve_full_mhz: true` and saw in vCenter that the VM had reserve CPU equal to the ESXi host it was deployed on. All other VMs had 0 MHz reservation.
<img width="586" alt="Screenshot 2024-07-23 at 12 18 16 PM" src="https://github.com/user-attachments/assets/a0f2525f-f788-4fc1-b8b1-7ecc424c03ea"><img width="846" alt="Screenshot 2024-07-23 at 12 18 35 PM" src="https://github.com/user-attachments/assets/1771fbe7-29ff-453d-b936-c6d9e3c9b669">

2024-07-23 19:32 UTC, ystros commented
Corresponding docs PR: https://github.com/cloudfoundry/docs-bosh/pull/846

2024-07-23 19:38 UTC, dsboulder commented
I wish it was a % of CPU to reserve, rather than just 0 or 100. Like I might choose to reserve 1 pCPU (which is in terms of physical ghz) for every 2 vCPUs to let the hyperthreading do its thing.

2024-07-23 20:31 UTC, dsboulder commented
Also what about taking the MIN(cpufreq) across the cluster rather than the largest node? Or we think they're the same usually?

2024-07-24 09:19 UTC, rkoster commented
@svrc as the author of the original PR, do you happen to remember the reasoning behind the current logic?

2024-08-08 14:38 UTC, jpalermo commented
@dsboulder & @rkoster doesn't seem like we're going to get a response on this. What direction do you want to go with it?

2024-09-11 19:34 UTC, jpalermo requested changes

2024-09-11 19:34 UTC, jpalermo commented on src/vsphere_cpi/lib/cloud/vsphere/resources/cluster.rb
> +      HOST_PROPERTIES = %w(name hardware.memorySize runtime.connectionState runtime.inMaintenanceMode runtime.powerState summary.hardware.cpuMhz)
HOST_PROPERTIES doesn't seem like it's used anymore and can be deleted rather than updated

2024-09-11 19:34 UTC, jpalermo commented on src/vsphere_cpi/lib/cloud/vsphere/vm_config.rb
> +
So we're finding the fastest cpu of any host in the cluster and saving that off. Then later, we're multiplying that by the number of CPUs in the VM type to get the actual "cpu_allocation" reservation.

This feels a bit odd. Shouldn't we just do the multiplication here of `host.summary.hardware.cpu_mhz` with `host.summary.hardware. num_cpu_cores` and then use that value later.

Not totally sure it matters in the end though. Is it a requirement that your "vm_type" number of CPUs matches exactly the number of cores in the host to be able to use this feature at all?

2024-09-12 14:43 UTC, jpalermo approved these changes
During FIWG discussion, it was decided that the feature "reserves the number of mhz * the number of cpus your vm type asks for" and the number of mhz is based on the largest host in the cluster you are targeting.

2024-09-12 14:43 UTC, merged

2024-10-11 02:02 UTC, svrc commented
Sorry for not responding earlier,  IIRC the logic for using the minimum CPU in the cluster is that you want to allow the workload to fit on any host in the cluster, not the largest host.   If you pick the largest host it will only be scheduled there.